### ISSUE TITLE
Exception thrown started on Sept 5th 2024.

### ISSUE THREAD

**Issue by blee2000** [HowardHinnant/date#840] opened 2024-09-15 02:13 UTC
For some reason this test case started to fail on Sept 5th 2024.

TEST(TZTest, Test_2023_GMT_end)
{
  using namespace date;

  std::istringstream utc{"2023-03-26 00:59:00.1234 UTC"};
  std::string tz;
  date::sys_time<std::chrono::microseconds> utc_tp;
  utc >> date::parse("%F %T%t%Z", utc_tp, tz);
  auto lon = date::make_zoned("Europe/London", utc_tp);
  auto london_dt=date::format("%F %T %Z", lon);
  auto london_tz=date::format("%Z", lon);
  EXPECT_EQ(london_tz, "GMT");

  auto local_time = lon.get_local_time();
  auto utc_time = lon.get_sys_time();
  auto dst_offset = std::chrono::duration_cast<std::chrono::hours>(local_time.time_since_epoch() - utc_time.time_since_epoch()).count();
  EXPECT_EQ(dst_offset, 0);
}

**Rule	Mexico	1931	only	-	April	30	0:00	1:00	D
Mexico         1931    1931    Jan/01                  00:00:00       00:00:00   
unknown file: Failure
C++ exception with description "oops: bad dow name: il	" thrown in the test body.**

**Comment by blee2000** [comment] 2024-09-15 02:16
this test case was running fine since Aug 2023, and then all of sudden failed on Sept 5th 2024.

**Comment by HowardHinnant** [comment] 2024-09-15 02:32
This is a duplicate of #836.

There are a few options for fixing it:

1.  Edit your IANA tzdata/northamercia file: change "April" to "Apr" on one (non comment) line (line 2634), or
2. Upgrade this library to the tip-of-master where parsing has been changed to accept "April", or
3. Talk the IANA maintainer (@eggert) into releasing 2024c which has already changed "April" to "Apr", but not yet been released.

**Comment by blee2000** [comment] 2024-09-15 02:47
thanks for your response.

Please note I don't use tzdata/northamercia or the library.  I only use tz.h and date.h.

**Comment by HowardHinnant** [comment] 2024-09-15 02:58
To cause this exception you must also be using tz.cpp: https://github.com/HowardHinnant/date/blob/master/src/tz.cpp#L862

This file, using the compile-time flags you are using, by default, downloads the latest version of the IANA timezone database (https://www.iana.org/time-zones) to your computer.  It is placed in various places on different platforms (perhaps "c:\Users\username\Downloads").  It is here you'll find tzdata/northamerica.  When 2024c is released by IANA, your  tzdata/northamerica will be replaced with the new version the first time you run an application that accesses this library.

**Comment by blee2000** [comment] 2024-09-15 03:01
sorry, I do link to this library called libdate-tz.a.  I will download the latest.  thank you!

**Comment by HowardHinnant** [comment] 2024-09-15 03:09
I'm not familiar with libdate-tz.a.  It is likely a distribution that builds this library independent of my knowledge (but perfectly acceptable).  They may or may not have picked up my fix to this issue what was committed only 3 days ago.

Sorry, as your issue notes, this is a fairly recent change causing this breakage.  Re-opening this issue so that it can be better tracked until you are up and running.

**Comment by blee2000** [comment] 2024-09-15 04:38
Hi Howard,

Please close the issue.  I am up and running.  thanks for your help.

**Closed** 2024-09-15 12:55 UTC

**Comment by basilgello** [comment] 2024-09-17 18:59
@HowardHinnant libdate-tz.a is likely from Debian and its derivatives (including Ubuntu). Would be great to have new version tagged, because despite declarations, C++20 support of tzdb in gcc 14 is implemented only for linux and *bsd.
