### ISSUE TITLE
Need clarification of feature difference from C++20

### ISSUE THREAD

**Issue by eyalroz** [HowardHinnant/date#633] opened 2020-12-25 13:58 UTC
Now that C++20 is standardized and starting to see some use, it is important IMHO to explain:

* which features of this library are missing from C++20
* which features of C++20 are missing from this library
* what the main differences between the two libraries are

**Comment by HowardHinnant** [comment] 2020-12-25 15:51
Duplicate of #565

**Closed by HowardHinnant** 2020-12-25 15:51 UTC
Labels: duplicate
