### ISSUE TITLE
date::zoned_time and vs2015 vs vs2017

### ISSUE THREAD

**Issue by mpietras** [HowardHinnant/date#353] opened 2018-06-18 13:25 UTC
The date-2.3 tz.h library compiles on vs2015 (v140) but not on vs2017 (v141) which indicates

```
include\date\tz.h(1634): error C2512: 'date::zoned_time<std::chrono::seconds,const date::time_zone *>': no appropriate default constructor available
include\date\tz.h(1634): note: No constructor could take the source type, or constructor overload resolution was ambiguous

```
yet date-2.4.1 tz.h library compiles on vs2017 (v141) but not on vs2015 (v140) which indicates:

```
include\date/tz.h(530): error C2535: 'date::zoned_time<std::chrono::duration<__int64,std::ratio<1,1>>,const char *>::zoned_time(TimeZonePtr,const std::chrono::time_point<std::chrono::system_clock,std::chrono::seconds> &)': member function already defined or declared
        with
        [
            TimeZonePtr=const char *
        ]
include\date/tz.h(393): note: see declaration of 'date::zoned_time<std::chrono::duration<__int64,std::ratio<1,1>>,const char *>::zoned_time'

```
Both seem to be reporting MSC_VER as 1914.  Aside from the obvious of using two different date versions, are there any straightforward changes to the most recent library we can do so it's functional on both compiler versions?

**Comment by HowardHinnant** [comment] 2018-06-18 14:13
VS compatibility is a constant challenge.  Could you try the current tip-of-trunk?  This may have already been fixed.

Thanks.

**Comment by mpietras** [comment] 2018-06-18 14:39
Thanks yeah, looks like same error on current master in vs2015 (different line number):

```
include\date/tz.h(534): error C2535: 'date::zoned_time<std::chrono::duration<__int64,std::ratio<1,1>>,const char *>::zoned_time(TimeZonePtr,const std::chrono::time_point<std::chrono::system_clock,std::chrono::seconds> &)': member function already defined or declared
        with
        [
            TimeZonePtr=const char *
        ]
include\date/tz.h(393): note: see declaration of 'date::zoned_time<std::chrono::duration<__int64,std::ratio<1,1>>,const char *>::zoned_time'

```

**Comment by HowardHinnant** [comment] 2018-06-18 14:53
Interesting.  I hadn't noticed this before, but in the error message: `TimeZonePtr=const char *`  may be a clue.  `TimeZonePtr` should never be `const char *`.  Normally `TimeZonePtr=const time_zone*`.  Could you post here a "Hello World" example that produces this error?

Thanks.

**Comment by mpietras** [comment] 2018-06-18 16:22
Yes, good clue indeed.  Turns out it's a simple as:

`date::zoned_seconds caltime = date::make_zoned( "test", date::local_days{ date::year{ 2018 } / 1 / 1 } );`

That const char * was presumably using a std::string conversion constructor previously... I'm sure I could fix with explicit conversions everywhere (I'm not using static strings in my code base but they're not std::strings either)...

**Comment by HowardHinnant** [comment] 2018-06-18 16:30
Thanks, I'll look into this...

**Comment by HowardHinnant** [comment] 2018-06-18 16:50
I think I know what the problem is.  But I'm not sure how to fix it.  I know how to work around it.

The problem is that the SFINAE-constraint on `template <class Duration, class TimeZonePtr> make_zoned()` doesn't work for VS, and is therefore #ifdef'd out.  So when you use `make_zoned`, `TimeZonePtr` gets deduced to `const char*`.

The work-around is to not use `make_zoned` to deduce the template argument types for `zoned_time`.  For `zoned_seconds`, this is actually not bad at all:

```
date::zoned_seconds caltime = { "test", date::local_days{ date::year{ 2018 } / 1 / 1 } };
```
For other precisions, it will be more of a pain:

```
date::zoned_time<std::chrono::milliseconds> caltime = { "test", date::local_days{ date::year{ 2018 } / 1 / 1 } };
```
Once you migrate to C++17, template deduction for constructors can be used:

```
date::zoned_time caltime = { "test", date::local_days{ date::year{ 2018 } / 1 / 1 } };
```

Indeed, the `make_zoned` helper functions are absent from the C++20 working draft because template deduction for constructors is actually easier to use than factory functions.

**Comment by d-frey** [comment] 2018-06-18 17:08
I remember a similar problem with Visual C++ because of missing expression SFINAE. I can't check it myself, but maybe you can enable the checks if you add dummy integers like this:

    template <class Duration, class TimeZonePtr, int = 1, ... >

(and, of course, `int=2`, `int=3`, etc. for the other versions).

**Comment by mpietras** [comment] 2018-06-18 17:23
Another interesting note, for what it's worth... using the deduced template method does solve the issue in the example, but exposes another (for my use case anyway).  In my example, I had explicitly declared the return type... but in my actual use I was using the auto keyword, which results in:

`cannot deduce type for 'auto' from 'initializer list'`

**Comment by HowardHinnant** [comment] 2018-06-18 17:29
Here's another syntax that should work for you:
```
auto caltime = date::zoned_seconds{ "test", date::local_days{ date::year{ 2018 } / 1 / 1 } };
```

**Comment by HowardHinnant** [comment] 2019-12-01 00:41
Closing.  Will reopen if someone confirms there's a problem and has code to fix it.

**Closed by HowardHinnant** 2019-12-01 00:41 UTC
