### ISSUE TITLE
tzdb as of 2024b causes exception on parsing

### ISSUE THREAD

**Issue by yamcenutzer** [HowardHinnant/date#841] opened 2024-09-18 15:20 UTC
On windows I use date.h/tz.h with remote_api. This always pulls the latzest tzdb.
As of Sept 5 2024, the new tzdb version 2024b seems to have changed the format and parsing causes an exception.
See here:
https://lists.iana.org/hyperkitty/list/tz-announce@iana.org/thread/IZ7AO6WRE3W3TWBL5IR6PMQUL433BQIE/

Manually downloading and using the previous version 2024a still works.
(I blame Mexico :-) )

**Comment by HowardHinnant** [comment] 2024-09-18 16:36
This is a duplicate of https://github.com/HowardHinnant/date/issues/836.

There are a few options for fixing it:

1. Edit your IANA tzdata/northamercia file: change "April" to "Apr" on one (non comment) line (line 2634), or
2. Upgrade this library to the tip-of-master where parsing has been changed to accept "April", or
3. Manually sticking with 2024a as you've already discussed, or
4. Talk the IANA maintainer (@eggert) into releasing 2024c which has already changed "April" to "Apr", but not yet been released.

Any one or more of these options will fix your issue, and be forward compatible.

**Closed** 2024-09-18 21:37 UTC
