### ISSUE TITLE
Unit Tests?

### ISSUE THREAD

**Issue by ecorm** [HowardHinnant/date#5] opened 2015-07-30 01:21 UTC
Any chance of unit tests being written for this library? Without them, I'm hesitant to use this library in our project. It seems to me there are tons of corner cases to worry about: leap years, months with less than 31 days, etc.

If I had more time, I would contribute such tests, but sadly I can't.

**Comment by HowardHinnant** [comment] 2015-07-30 02:04
YES!  Just haven't had the time.  But definitely yes.  I actually just wrote the first few unit tests this evening.  I'm not quite yet ready to push them to github, but by the end of this weekend I hope to have a big drop of unit tests.

Normally I would do unit tests much earlier in the process.  I just dropped the ball on that, and have no excuse.  I did test while developing.  I just didn't set up a systematic test harness.  Some of this is evidenced by my participation in this thread on the IANA timezone database discussion list:

http://mm.icann.org/pipermail/tz/2015-July/022448.html

where I participated in helping set up a generic validation timezone transition list that different parsers can check against.

Many of the unit tests for date.h will require C++14, as they will be compile-time tests.  This will be fine for clang and gcc, but VS-2015 won't pass them.  However the date.h code is *highly* portable, so I'm not really worried about VS-2015.

**Comment by HowardHinnant** [comment] 2015-07-30 02:12
Oh, further info on testing.  The really hairy date computation algorithms all come from here:

http://howardhinnant.github.io/date_algorithms.html

And detailed unit tests for those algorithms are presented right in that paper.  These include the conversions between `year_month_day` and `day_point`, going both ways, which in the algorithms paper are called `days_from_civil` and `civil_from_days`.  The algorithms paper demonstrates a unit test that assures these algorithms are working over a range of +/- a million years.  Though date.h, because of using an `int16_t` to store the year, maxes out at +/- 32K years.

So I have a lot of confidence in the date computation aspect of this library (not that unit tests are needed, they are).

**Comment by HowardHinnant** [comment] 2015-07-30 03:13
One final comment:  I'm realizing in hindsight that I've made comments above that sound like "the tests won't pass on C++11 or VS-2015, don't worry".  And I want to explain those remarks.

date.h has code like this:
````
CONSTCD14
inline
year_month_day::operator day_point() const noexcept
{
    static_assert(std::numeric_limits<unsigned>::digits >= 18,
             "This algorithm has not been ported to a 16 bit unsigned integer");
    static_assert(std::numeric_limits<int>::digits >= 20,
             "This algorithm has not been ported to a 16 bit signed integer");
    auto const y = static_cast<int>(y_) - (m_ <= feb);
    auto const m = static_cast<unsigned>(m_);
    auto const d = static_cast<unsigned>(d_);
    auto const era = (y >= 0 ? y : y-399) / 400;
    auto const yoe = static_cast<unsigned>(y - era * 400);       // [0, 399]
    auto const doy = (153*(m + (m > 2 ? -3u : 9)) + 2)/5 + d-1;  // [0, 365]
    auto const doe = yoe * 365 + yoe/4 - yoe/100 + doy;          // [0, 146096]
    return day_point{days{era * 146097 + static_cast<int>(doe) - 719468}};
}
````
This is the `days_from_civil` algorithm from:
http://howardhinnant.github.io/date_algorithms.html#days_from_civil
The macro `CONSTCD14` will expand to `constexpr` when the compiler is in -std=c++14 mode, and otherwise expand to nothing at all.  This means that this function in C++14 can execute at compile time or run time, and in C++11 can only execute at run time.  But either way, the same code gets executed.  Therefore a C++11 run time test can be tested at compile time in C++14.  There's nothing more mysterious about my remarks than that.

**Comment by mavam** [comment] 2015-07-30 03:49
:+1: 
Looking forward to the unit tests as well. I was about to ask the same, as I'm planning to use the date library in a project soon.

**Comment by ecorm** [comment] 2015-07-30 04:28
Thanks @HowardHinnant. By the sound of it, the unit tests will be done by the time we are ready to deploy our product this winter.

> Many of the unit tests for date.h will require C++14, as they will be compile-time tests. This will be fine for clang and gcc, but VS-2015 won't pass them. However the date.h code is highly portable, so I'm not really worried about VS-2015.

If possible, please use `#ifdef` directives to leave out those tests on platforms that don't support C++14.

You probably thought of this already, but I'm sure you could mine Boost.DateTime for ideas on test cases.

**Comment by HowardHinnant** [comment] 2015-08-02 20:01
There's still a long way to go, but here is the start of it:

https://github.com/HowardHinnant/date/tree/test

For now it is on a separate branch just to be sure that I don't step on some other important work that is ongoing (a VS port by gmcode -- https://github.com/gmcode/date/commits/gmchanges2).

**Comment by HowardHinnant** [comment] 2015-08-10 02:10
Unit tests are now on the master branch, and still a work in progress.

**Comment by ecorm** [comment] 2015-08-10 23:55
That's a great start @HowardHinnant , thank you! I assume there will be test cases for leap years/days added in the future?

I'll try to find time to run these tests on my platforms, and will report back if there are problems.

**Comment by HowardHinnant** [comment] 2015-08-11 00:22
There are definitely more tests to come, but I suspect the test you're looking for is here: https://github.com/HowardHinnant/date/blob/master/test/date_test/year_month_day.pass.cpp#L128-L158

This tests every date in the range `[-1000_y/jan/1, 3000_y/dec/31]`.  For each date there is a conversion from `year_month_day` to `day_point`.  That `day_point` is tested to be 1 greater than the previous `day_point`.  The `day_point` is converted to a `weekday`, and that `weekday` is tested to be the day after the previous `weekday`.  And finally the `day_point` is converted back to a `year_month_day`, and that result is tested to be equal to the original `year_month_day` for the iteration.

This combined with a spot-check such as this https://github.com/HowardHinnant/date/blob/master/test/date_test/year_month_day.pass.cpp#L180-L193 which nails down `1969_y/dec/31` == day_point{-1}` completely nails everything for 4000 years.

I'm still lacking tests for `year::is_leap()` though if that is what you're referring to.  Or if you have another test in mind, let me know.

I also still need to add a disclaimer about VS in there.  VS because of its substandard `constexpr` support, is not going to compile these tests.  However I anticipate VS will do much better on the timezone side as there won't be many (any?) compile time tests over there.

**Comment by ecorm** [comment] 2015-08-11 01:26
I was scanning `year_month_day.pass.cpp` for the words "leap", and "Feb 29", which led me to believe you weren't testing leap days/years.

In addition to `year::is_leap()`, I was also thinking along the lines of checking that:
- `2000_y/feb/29` is `ok` (2000 is a leap year)
- `2100_y/feb/29` is `!ok` (2100 is not a leap year)
- `2100_y/feb/28 + 1_d == 2100_y/mar/1`
- `2000_y/mar/1 - 2000_y/feb/28 ==  2_d`
- `2100_y/mar/1 - 2100_y/feb/28 ==  1_d`
- The last day of `2000_y/feb` is indeed the 29th (sorry, I'm not yet familiar with your `*_last` facilities)

I don't know if it's safe to assume that your date-sweeping loop covers the test cases above.

**Comment by HowardHinnant** [comment] 2015-08-11 01:38
Those look like good tests to me.  I'll add them in.  Thanks!

**Comment by HowardHinnant** [comment] 2015-09-06 16:42
Closing as I believe we have decent unit tests now.  However requests for specific unit tests or regression tests are always welcome.

**Closed by HowardHinnant** 2015-09-06 16:42 UTC

**Comment by ecorm** [comment] 2015-09-08 16:40
Thanks!
