### ISSUE TITLE
POSIX Timezone Parsing assert fails if no rule is  specified

### ISSUE THREAD

**Issue by figaro-smartotum** [HowardHinnant/date#860] opened 2024-12-06 19:36 UTC
```
Library Version v3.0.3
GCC 13.2 (arm-none-eabi), same on GCC 14.1.1 (x86_64-linux-gnu)
```

I am working on embedded platform, and 
1) I cannot use exceptions
2) I do not have a POSIX filesystem implementation,
for these reasons I cannot use the complete `tz` implementation and I ended up by removing the (few) throws from `pth.z` and hard-coding a map of `<Timezone, POSIX Timezone strings`>

Anyway I noticed that, if no DST rule is specified on the posix string (i.e `Posix::time_zone tz{"GMT0"}`)  the assert on line 513 of `ptz.h` fails.

Tthe condition not met is `st < r.end`, since in this case `constant_offset()` assigns
 `r.end   = sys_days{year::max()/December/last};`,
It is easy to reproduce the issue:
```C++
#include <iostream>
#include "date/ptz.h"

int main() {

    using namespace date;

    constexpr const char *POSIX_AFRICA_CASABLANCA = "WET0WEST,M3.5.0,M10.5.0/3";
    constexpr const char *POSIX_GMT0 = "GMT0";

    Posix::time_zone casablanca_tz {POSIX_AFRICA_CASABLANCA};
    Posix::time_zone gmt_tz {POSIX_GMT0};

    std::cout << "Africa/Casablanca :" << zoned_time{casablanca_tz, std::chrono::system_clock::now()}<<std::endl;

    std::cout << "GMT0:" << zoned_time{gmt_tz, std::chrono::system_clock::now()}<<std::endl;
    /*
     * Assertion `r.begin <= st && st < r.end' failed.
     */

    return 0;
}

```

**Comment by HowardHinnant** [comment] 2024-12-06 23:37
Thanks much for this quality bug report.  I've just pushed a fix to the master branch which I believe fixes this problem.  If this works for you I will include it in the next release.

**Closed** 2024-12-06 23:36 UTC

**Comment by figaro-smartotum** [comment] 2024-12-07 04:44
I confirm the bug is fixed for me on master. Great job!
I was wondering if a release that allows the possibility to disable the exceptions even for the `ptz` part (for me even an abort() call into the `throw_invalid` could be fine). Because I noticed  that `throw_invalid` wraps almost everything, but not everything (i.e. `time_zone::to_sys` directly throws).

It would be really useful for everything that uses the library in small microcontrollers that compile with `-fno-exceptions` (and microcontrollers always lack for a good timezone support).

**Comment by HowardHinnant** [comment] 2024-12-07 14:33
I think we could do that for ptz.  I only have Apple clang to test on.  It looks like without `-fno-exceptions` we have:

```
#define __EXCEPTIONS 1
#define __cpp_exceptions 199711L
```

And with `-fno-exceptions` these macros are not defined.  If that is consistent with gcc we could just `#ifdef` on one of those to decide whether to `throw` or `abort`.

Would sending the same string as is put into `runtime_error` to `stderr` be helpful just prior to the `abort`?

**Comment by lrodorigo** [comment] 2024-12-09 07:44
I can confirm that both defines are also valid for gcc.
It could be useful something like

```
#ifndef DATE_HAS_EXCEPTIONS
   #define DATE_HAS_EXCEPTIONS __EXCEPTIONS
#endif
```

Such that the user has the final control on the exceptions behaviour.

For embedded platforms `stderr` could be not defined at all (in my case [STM32 with newlib nano] it it segfaulting, while the printf is properly overridden). 

I suggest just an  `assert(message)` just before the abort (the assert is usually skipped in release mode).
