### ISSUE TITLE
Strange parsing rules for parse("%FT%R")

### ISSUE THREAD

**Issue by jamespmonaco** [HowardHinnant/date#480] opened 2019-08-23 16:29 UTC
I noticed some strange behaviour when using the following to parse a date string:
```
date::local_time<std::chrono::nanoseconds> local_tp;
std::istringstream instream(str);
instream >> date::parse("%FT%R", local_tp);
```

The following strings (str) parse correctly and do not set the failbit.
2018-05-09T01:01
2018-05-09T1:11
2018-05-09T11:2.3212
2018-05-09T1:01
2018-05-09T11:01

The following strings fail and set the failbit
2018-05-09T01:1
2018-05-09T1:1
2018-05-09T11:1

For now, I will enforce the two digits for both hours and minutes.  Perhaps this is what was intended anyway.

Thanks!  And BTW, it's really impressive all you've developed!

**Comment by HowardHinnant** [comment] 2019-08-23 17:35
We have a minor mystery.  I just tested:
```
#include "date/date.h"
#include <iostream>
#include <sstream>

int
main()
{
    using namespace date;
    using namespace std;
    using namespace std::chrono;
    istringstream in{"2018-05-09T01:1"};
    local_time<nanoseconds> tp;
    in >> parse("%FT%R", tp);
    if (in.fail())
        cout << "fail\n";
    else
        cout << tp << '\n';
}
```
And the output was:
```
2018-05-09 01:01:00.000000000
```
My git commit is at 255473c929a4360fa750f949b233e49f24d1cef0.

**Comment by HowardHinnant** [comment] 2019-08-23 17:40
I'll bet I need to make a new release.  It has been forever since the last one...

**Comment by jamespmonaco** [comment] 2019-08-23 17:48
Thanks!  I get the same from your code.  I will investigate further.

**Comment by jamespmonaco** [comment] 2019-08-23 19:01
OK, I think I got to the bottom of things.  In short the problem is me, or at least my incomplete understanding of istringstream behaviour.  I wanted to detect if a time string like "2018-05-09T01:01" had any trailing characters, e..g "2018-05-09T01:01xxx", so I could invalidate it.  I was using tellg() or eof() to try to detect this.  But this is not working as I expected, and lead to the erroneous conclusions I stated previously.  See the following code and output:
```
#include "date/date.h"
#include <iostream>
#include <sstream>
#include <algorithm>

int
main()
{
    using namespace date;
    using namespace std;
    using namespace std::chrono;


    istringstream in1 {"2018-05-09T01:1"};
    local_time<nanoseconds> tp;
    in1 >> parse("%FT%R", tp);
    if (in1.fail())
        cout << "fail\n";
    else
        cout << tp << '\n';

    if (in1.eof())
        cout << "EOF" << '\n';
    else
        cout << "Not EOF" << '\n';


    istringstream in2 {"2018-05-09T01:01"};
    in2 >> parse("%FT%R", tp);
    if (in2.fail())
        cout << "fail\n";
    else
        cout << tp << '\n';

    if (in2.eof())
        cout << "EOF" << '\n';
    else 
        cout << "Not EOF" << '\n';

}
```
The output is
```
2018-05-09 01:01:00.000000000
EOF
2018-05-09 01:01:00.000000000
Not EOF
```

I didn't expect this difference.

**Comment by HowardHinnant** [comment] 2019-08-23 19:14
Ah, yes.  This is expected behavior because the %M field demands to read one digit and refuses to read more than two.  So the first looks for a digit after ":1" and finds EOF, whereas the second doesn't even glance beyond ":01" and thus doesn't flag the EOF.

**Comment by HowardHinnant** [comment] 2019-08-23 19:56
Ok, long story:

There's a way to get the behavior you want by taking advantage of a little-known trick.  When the fmt string in `parse` sees a space character, that matches _0 or more_ spaces.  By putting a space at the end of the fmt string, you can force the parser to keep looking for spaces until it hits EOF:  `"%FT%R "`.

However, sigh, there's a bug in the code associated with that logic.  I just pushed a fix for it:  https://github.com/HowardHinnant/date/commit/141ba85614489c03e3a4a791f7af48eab8f660fa

**Comment by jamespmonaco** [comment] 2019-08-23 20:05
Great, thanks!  Another possible work around seems to be
```
if (in1.fail() || in1.peek()!=-1) // careful: peek at EOF triggers failbit
{... // reached EOF
}
```
I like yours better though.

**Comment by jamespmonaco** [comment] 2019-08-23 20:06
Sorry, I didn't mean to close it.  I'll leave that up to you.  But you've more than answered my question and I really appreciate it!

**Closed** 2019-08-23 20:16 UTC
