### ISSUE TITLE
time_point<system_clock, nanoseconds> may lead to overflow in tz.h

### ISSUE THREAD

**Issue by wuxian08** [HowardHinnant/date#17] opened 2015-10-19 09:12 UTC
In line 336 of function ```Zone::to_sys_impl()```, when the function argument ```tp``` is of type ```time_point<system_clock, nanoseconds>``` and ```get_info()``` returns the zonelet info ```i``` such that ```i.end``` achieves ```max``` (in year 6052 or something),  ```i.end(second_point = time_point<system_clock, seconds>)``` is first converted into ```time_point<system_clock, nanoseconds>```, which leads to overflow. 

A feasible solution could be casting ```tp``` to ```time_point<system_clock, microseconds>``` or you might consider to limit the type of ```tp```.

**Comment by HowardHinnant** [comment] 2015-10-19 18:38
One of the features of this function is to return the precision of the input (if the input is finer than seconds), which makes overflow for nanoseconds all but inevitable.  But I know that this is a very easy mistake to make.  Perhaps I should range check and throw an overflow exception with a detailed message.  This would enable the caller to decide to either shorten the range or coarsen the precision.

Thanks for the report.  I'll definitely do something about this.

**Comment by HowardHinnant** [comment] 2015-11-04 00:48
Thanks again for the report.  I misunderstood it when I first saw it, but I'm certain I have a handle on it now.  This should fix it:
https://github.com/HowardHinnant/date/commit/f19e7f22c734f098c2c569667ffba6dfb1844cc0
I'm closing this, but if you find that the issue is not solved, please don't hesitate to reopen this issue.

**Closed by HowardHinnant** 2015-11-04 00:48 UTC

**Comment by wuxian08** [comment] 2015-11-04 01:40
That's  exactly what I asked for. Thanks :)
