### ISSUE TITLE
check in c++ version in date.h

### ISSUE THREAD

**Issue by Tudyx** [HowardHinnant/date#649] opened 2021-02-25 10:58 UTC
In the if condition on `__cplusplus`  line 138 of date.h, shouldn't be `>=` instead of `>`?

```C++
#ifndef HAS_UNCAUGHT_EXCEPTIONS
#  if __cplusplus > 201703 || (defined(_MSVC_LANG) && _MSVC_LANG > 201703L)
#    define HAS_UNCAUGHT_EXCEPTIONS 1
#  else
#    define HAS_UNCAUGHT_EXCEPTIONS 0
#  endif
#endif  // HAS_UNCAUGHT_EXCEPTIONS
```

**Comment by HowardHinnant** [comment] 2021-02-25 14:32
Duplicate of https://github.com/HowardHinnant/date/issues/435

**Closed by HowardHinnant** 2021-02-25 14:32 UTC
